import fs from "node:fs";
import path from "node:path";
import { ensureDir } from "../shared/fs.js";
import { interpolate } from "../config/interpolate.js";

const GENERATED_HEADER = "# Generated by Devlane. Do not edit manually.";

export function buildRuntimeContext(config, ports) {
  const variables = {};
  const urls = { apps: {}, services: {} };

  for (const [key, binding] of Object.entries(ports)) {
    const [kind, name] = key.split(".");
    variables[`${kind}.${name}.hostPort`] = binding.hostPort;
    variables[`${kind}.${name}.internalPort`] = binding.internalPort;

    if (kind === "apps") {
      const url = `http://localhost:${binding.hostPort}`;
      urls.apps[name] = url;
      variables[`apps.${name}.url`] = url;
    }

    if (kind === "services") {
      const service = config.services[name];
      const url = serviceUrl(service, binding);
      if (url) {
        urls.services[name] = url;
        variables[`services.${name}.url`] = url;
      }
    }
  }

  return { variables, urls };
}

export function buildEnvironmentVariables(config, context, options = {}) {
  const baseEnv = interpolate(config.env ?? {}, context.variables);

  for (const [name, binding] of Object.entries(serviceBindings(context))) {
    const service = config.services[name];
    const url = serviceUrl(service, binding, {
      target: options.target ?? "host",
      runtimeDriver: config.runtime?.driver
    });
    const key = `${name.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_URL`;
    baseEnv[key] = url;
  }

  return baseEnv;
}

export function appEnvironment(config, appName, context) {
  const app = config.apps[appName];
  const binding = context.bindingLookup[`apps.${appName}`];
  return {
    ...buildEnvironmentVariables(config, context, { target: "runtime" }),
    ...interpolate(app.env ?? {}, context.variables),
    ...(binding ? { PORT: String(portForTarget(binding, { target: "runtime", runtimeDriver: config.runtime?.driver })) } : {})
  };
}

export function writeContextFiles(record, config, context) {
  const files = [];

  for (const relative of config.context.files) {
    const filePath = path.join(record.worktreePath, relative);
    ensureDir(path.dirname(filePath));

    if (relative.endsWith(".env") || relative.endsWith(".env.local")) {
      fs.writeFileSync(filePath, renderEnvFile(record, config, context));
    } else {
      fs.writeFileSync(filePath, renderMarkdownContext(record, context));
    }

    files.push(filePath);
  }

  return files;
}

export function renderMarkdownContext(record, context) {
  const lines = [
    "# Devlane Environment",
    "",
    GENERATED_HEADER,
    "",
    `Status: ${record.status}`,
    `Environment ID: ${record.id}`,
    "",
    "## Apps",
    ""
  ];

  if (Object.keys(context.urls.apps).length === 0) {
    lines.push("- none");
  } else {
    for (const [name, url] of Object.entries(context.urls.apps)) {
      lines.push(`- ${name}: ${url}`);
    }
  }

  lines.push("", "## Services", "");

  if (Object.keys(context.urls.services).length === 0) {
    lines.push("- none");
  } else {
    for (const [name, url] of Object.entries(context.urls.services)) {
      lines.push(`- ${name}: ${url}`);
    }
  }

  lines.push(
    "",
    "## Commands",
    "",
    "- `devlane status`",
    "- `devlane logs api`",
    "- `devlane destroy`",
    "",
    "## Agent Guidance",
    "",
    "Use the service URLs above. Do not start duplicate infrastructure unless explicitly asked."
  );

  return `${lines.join("\n")}\n`;
}

export function renderEnvFile(record, config, context) {
  const env = {
    ...buildEnvironmentVariables(config, context),
    DEVLANE_ENV_ID: record.id
  };

  for (const [name, url] of Object.entries(context.urls.apps)) {
    env[`${name.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_URL`] = url;
  }

  return `${GENERATED_HEADER}\n${Object.entries(env)
    .map(([key, value]) => `${key}=${shellEscape(String(value))}`)
    .join("\n")}\n`;
}

function serviceUrl(service, binding, options = {}) {
  if (service.url) {
    return interpolate(service.url, {
      "service.hostPort": binding.hostPort,
      "service.internalPort": binding.internalPort
    });
  }

  const port = portForTarget(binding, options);

  if (service.type === "postgres") {
    const env = service.env ?? {};
    const user = env.POSTGRES_USER ?? "postgres";
    const password = env.POSTGRES_PASSWORD ?? "postgres";
    const database = env.POSTGRES_DB ?? user;
    return `postgres://${user}:${password}@localhost:${port}/${database}`;
  }

  if (service.type === "redis") {
    return `redis://localhost:${port}`;
  }

  return `tcp://localhost:${port}`;
}

function serviceBindings(context) {
  return Object.fromEntries(
    Object.entries(context.bindingLookup ?? {})
      .filter(([key]) => key.startsWith("services."))
      .map(([key, binding]) => [key.slice("services.".length), binding])
  );
}

function portForTarget(binding, options = {}) {
  if (options.target === "runtime" && options.runtimeDriver === "smolmachines") {
    return binding.internalPort;
  }

  return binding.hostPort;
}

function shellEscape(value) {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) return value;
  return JSON.stringify(value);
}
